Add OpenAPI doc generation and client generation
k8ssandra/management-api-for-apache-cassandra pull request #164
Opened 2021-11-10 22:59 UTC by emerkle826

Fixes #151 and #152 

The Swagger maven plugin will generate the OepnAPI spec doc based on the actual JAX-RS code/annotations. The OpenAPI maven plugin will then generate a Go client based on the openapi.json spec file created by the Swagger plugin.

2021-12-03 15:29 UTC, emerkle826 commented
I'll remove the Go client generation bits from this PR as #151 will take a bit more work at this point.

2021-12-03 16:16 UTC, jdonenine commented
Discussed this morning, @emerkle826 is going to reorganize this PR a bit so that the code generation isn't tangled up with the API spec corrections.  We'll follow up with the code generation pieces separately.  Once that cleanup happens we can pull this out of draft mode and get it reviewed.

2021-12-16 20:49 UTC, jdonenine requested changes
We chatted offline about the request/response MIME types, Erik will try to get those updated where possible and then we're good to go with this.

The ultimate spec parses properly in Swagger editor and could be used to generate a few different client libraries.  Very nice upgrade here, step one!

2021-12-17 16:28 UTC, emerkle826 commented on management-api-server/src/main/java/com/datastax/mgmtapi/resources/K8OperatorResources.java
>      public Response checkClusterConsistency(@QueryParam(value="consistency_level")String consistencyLevelStr, @QueryParam(value = "rf_per_dc") Integer rfPerDcVal)
That may be because it produces "text/plain" for 200 response, and "application/json" for a 500 response

2022-01-04 18:05 UTC, jdonenine approved these changes
Thanks for making all these last changes, way better place than we started here.

2022-01-04 18:37 UTC, merged